lib/phx_blog_web/router.ex
defmodule PhxBlogWeb.Router do
  use PhxBlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :login_session do
    plug PhxBlog.Auth.LoginSessionPipeline
  end

  pipeline :ensure_auth do
    plug PhxBlog.Auth.EnsureAuthPipeline
  end

  pipeline :ensure_not_auth do
    plug PhxBlog.Auth.EnsureNotAuthPipeline
  end

  scope "/admin", PhxBlogWeb.Admin, as: :admin do
    pipe_through [:browser, :login_session, :ensure_auth]

    get "/", ArticleController, :index, as: :root
    resources "/articles", ArticleController, only: [:index, :new, :create]
    delete "/logout", SessionController, :delete, as: :logout
  end

  scope "/admin", PhxBlogWeb.Admin, as: :admin do
    pipe_through [:browser, :login_session, :ensure_not_auth]

    get "/login", SessionController, :new, as: :login
    post "/login", SessionController, :create, as: :login
  end

  scope "/", PhxBlogWeb do
    pipe_through [:browser, :login_session]

    resources "/", ArticleController, only: [:index]
  end
end

lib/phx_blog_web/views/layout_view.ex
defmodule PhxBlogWeb.LayoutView do
  use PhxBlogWeb, :view
end

lib/phx_blog_web/templates/layout/admin.html.eex
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PhxBlog Admin</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills">
            <li><%= link "記事管理", to: admin_root_path(@conn, :index) %> </li>
            <li><%= link "ログアウト", to: admin_logout_path(@conn, :delete), method: :delete %> </li>
          </ul>
        </nav>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= @conn.assigns[:current_admin].email %>
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/phx_blog_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello PhxBlog!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>